version: '2'
services:
    maddy:
      image: foxcpp/maddy:latest
      restart: always
      environment:
        -PUID=1000
        -PGID=1000
        -MADDY_HOSTNAME=mail.stark.dog
        -MADDY_DOMAIN=stark.dog
      volumes:
        /data:/data
      container_name: maddy
      labels:
        - traefik.enable=true
        - traefik.http.routers.mail.entrypoints=web
        - traefik.http.routers.mail.rule=Host(`mail.stark.dog`)
        - traefik.http.routers.mail.middlewares=redirect@file
        - traefik.http.routers.mail.priority=1

        # https
        - traefik.http.routers.mail-secure.entrypoints=web-secure
        - traefik.http.routers.mail-secure.rule=Host(`mail.stark.dog`)
        - traefik.http.routers.mail-secure.tls=true
        - traefik.http.routers.mail-secure.service=mail-svc
        - traefik.docker.network=traefik
        # service
        - traefik.http.services.mail-svc.loadbalancer.server.port=8000

        # add to router
        #- traefik.http.routers.mail-secure.middlewares=traefik-forward-auth@file,secure-frame-header@file
        - traefik.http.routers.mail-secure.middlewares=secure-frame-header@file


networks:
  default:
    name: traefik
    external: true
