version: '3.1'

services:
  sonarr:
    image: linuxserver/sonarr
    restart: always
    # ports:
    #   - "8989:8989"
    environment:
      - PUID=1001
      - PGID=1001

    volumes:
      - /dev/rtc:/dev/rtc:ro
      - ~/docker/sonarr/config:/config
      - /mnt/Storage_And_Media/media/:/media/
    container_name: sonarr
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.routers.sonarr.rule=Host(`sonarr.stark.dog`)
      - traefik.http.routers.sonarr.middlewares=redirect@file
      - traefik.http.routers.sonarr.priority=1

      # https
      - traefik.http.routers.sonarr-secure.entrypoints=web-secure
      - traefik.http.routers.sonarr-secure.rule=Host(`sonarr.stark.dog`)
      - traefik.http.routers.sonarr-secure.tls=true
      - traefik.http.routers.sonarr-secure.service=sonarr-svc
      - traefik.docker.network=traefik
      # service
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989

      # add to router
      - traefik.http.routers.sonarr-secure.middlewares=traefik-forward-auth@file,secure-frame-header@file
      #- traefik.http.routers.sonarr-secure.middlewares=traefik-forward-auth@file
     
networks:
  default:
    name: traefik
    external: true
