version: "3.3"

services:
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.2.0-arm
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://auth.stark.dog/auth/realms/starkdog
      - PROVIDERS_OIDC_CLIENT_ID=traefik
      - PROVIDERS_OIDC_CLIENT_SECRET=TLKNSlOzcZYWSuDKAZKDoZ2MSnW98CmO
      - SECRET=is87g4987vgo748g
      # INSECURE_COOKIE is required if not using a https entrypoint
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
  whoami:
    image: nginxdemos/hello
    container_name: whoami
    ports: 
      - 8888:80
    labels:
      # - traefik.frontend.rule=Host:whoami.stark.dog
      # - traefik.port=80
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.rule=Host(`whoami.stark.dog`)
      - traefik.http.routers.whoami.middlewares=redirect@file
      - traefik.http.routers.whoami.priority=1

      #https
      - traefik.http.routers.whoami-secure.entrypoints=web-secure
      - traefik.http.routers.whoami-secure.rule=Host(`whoami.stark.dog`)
      - traefik.http.routers.whoami-secure.tls=true
      - traefik.http.routers.whoami-secure.service=whoami-svc
      - traefik.docker.network=traefik
      # service
      - traefik.http.services.whoami-svc.loadbalancer.server.port=80

      # add to router
      - traefik.http.routers.whoami-secure.middlewares=traefik-forward-auth@file
networks:
  default:
    name: traefik
    external: true