version: "2"
services:
  organizr:
    image: organizr/organizr
    container_name: organizer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - fpm=true
      - branch=v2-master
    volumes:
      - ~/docker/organizer/config:/config
    # ports:
    #   - 81:80
    restart: unless-stopped
    labels:
      - traefik.enable=true  
      - traefik.http.routers.organizr.entrypoints=web
      - traefik.http.routers.organizr.rule=Host(`home.stark.dog`)
      - traefik.http.routers.organizr.middlewares=redirect@file
      - traefik.http.routers.organizr.priority=1

      # https
      - traefik.http.routers.organizr-secure.entrypoints=web-secure
      - traefik.http.routers.organizr-secure.rule=Host(`home.stark.dog`)
      - traefik.http.routers.organizr-secure.tls=true
      - traefik.http.routers.organizr-secure.service=organizr-svc
      - traefik.docker.network=traefik

      # service
      - traefik.http.services.organizr-svc.loadbalancer.server.port=80

      # add to router
      #- traefik.http.routers.organizr-secure.middlewares=traefik-forward-auth@file,secure-frame-header@file
      - traefik.http.routers.organizr-secure.middlewares=secure-frame-header@file
networks:
  default:
    name: traefik
    external: true
