version: "2.1"
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:1.6.3-ls16
    # build:
    #   context: /home/stark/dockeremu/docker-emulatorjs
    #   dockerfile: Dockerfile
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
    volumes:
      - /home/stark/docker/emulator/config:/config
      - /mnt/Storage_And_Media/media/games:/data
    ports:
      - 3001:3000
    #   #- 81:80
    # #   - 4001:4001 #optional
    labels:
      - traefik.enable=true
      - traefik.http.routers.emu.entrypoints=web
      - traefik.http.routers.emu.rule=Host(`emu.stark.dog`)
      - traefik.http.routers.emu.middlewares=redirect@file
      - traefik.http.routers.emu.priority=1

      # https
      - traefik.http.routers.emu-secure.entrypoints=web-secure
      - traefik.http.routers.emu-secure.rule=Host(`emu.stark.dog`)
      - traefik.http.routers.emu-secure.tls=true
      - traefik.http.routers.emu-secure.service=emu-svc
      - traefik.docker.network=traefik
      # service
      - traefik.http.services.emu-svc.loadbalancer.server.port=80

      # add to router
      - traefik.http.routers.emu-secure.middlewares=secure-frame-header@file
    restart: unless-stopped
networks:
  default:
    name: traefik
    external: true