version: "3.3"

services:

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped 
    ports:
      - 80:80
      - 443:443
      - 8448:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/stark/docker/traefik/config/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "/home/stark/docker/traefik/config/dynamic_conf.toml:/etc/traefik/dynamic_conf.toml:ro"
      - "/home/stark/docker/letsencrypt/certs/live/stark.dog-0001/fullchain.pem:/etc/traefik/certs/starkdog-full.pem:ro"
      - "/home/stark/docker/letsencrypt/certs/live/stark.dog-0001/privkey.pem:/etc/traefik/certs/starkdog-priv.pem:ro"

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.stark.dog`)
      - traefik.http.routers.traefik.middlewares=redirect@file
      - traefik.http.routers.traefik.priority=1

      #https
      - traefik.http.routers.traefik-secure.entrypoints=web-secure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.stark.dog`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.service=traefik-svc
      - traefik.docker.network=traefik

      # service
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080

      # add to router
      - traefik.http.routers.traefik-secure.middlewares=secure-frame-header@file
      #- traefik.http.routers.traefik-secure-auth.middlewares=authentik@docker


networks:
  default:
    name: traefik
    external: true