version: '3.1'

services:
  radarr:
    image: linuxserver/radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker/radarr/config:/config
      - /mnt/Storage_And_Media/usenet/downloads:/downloads
      - /mnt/Storage_And_Media/media/movies:/movies
    container_name: radarr
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.rule=Host(`radarr.stark.dog`)
      - traefik.http.routers.radarr.middlewares=redirect@file
      - traefik.http.routers.radarr.priority=1

      # https
      - traefik.http.routers.radarr-secure.entrypoints=web-secure
      - traefik.http.routers.radarr-secure.rule=Host(`radarr.stark.dog`)
      - traefik.http.routers.radarr-secure.tls=true
      - traefik.http.routers.radarr-secure.service=radarr-svc
      - traefik.docker.network=traefik

      # service
      - traefik.http.services.radarr-svc.loadbalancer.server.port=7878

      # add to router
      - traefik.http.routers.radarr-secure.middlewares=secure-frame-header@file

networks:
   default:
     external:
       name: traefik
