version: "2.1"
services:
  mylar:
    image: ghcr.io/linuxserver/mylar3:latest
    container_name: mylar
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config:/config
      - /mnt/Storage_And_Media/media/comics:/comics
      - /mnt/Storage_And_Media/usenet/downloads:/downloads
    ports:
        - 8090:8090
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mylar.entrypoints=web
      - traefik.http.routers.mylar.rule=Host(`mylar.stark.dog`)
      - traefik.http.routers.mylar.middlewares=redirect@file
      - traefik.http.routers.mylar.priority=1

      # https
      - traefik.http.routers.mylar-secure.entrypoints=web-secure
      - traefik.http.routers.mylar-secure.rule=Host(`mylar.stark.dog`)
      - traefik.http.routers.mylar-secure.tls=true
      - traefik.http.routers.mylar-secure.service=mylar-svc
      - traefik.docker.network=traefik
      # service
      - traefik.http.services.mylar-svc.loadbalancer.server.port=8090

      # add to router
      #- traefik.http.routers.mylar-secure.middlewares=traefik-forward-auth@file,secure-frame-header@file
      - traefik.http.routers.mylar-secure.middlewares=secure-frame-header@file
     
networks:
  default:
    name: traefik
    external: true